name: Build and Deploy WordPress

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ./wordpress
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Deploy to Swarm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SWARM_HOST }}
        username: ${{ secrets.SWARM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stack deploy -c /docker/stacks/${{ github.event.repository.name }}/docker-compose.yml ${{ github.event.repository.name }}
