name: Build and Deploy WordPress

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set lowercase image tag
      id: lowercase
      run: |
        echo "repo=$(echo $GHCR_IMAGE | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ./wordpress
        push: true
        tags: ${{ steps.lowercase.outputs.repo }}:latest
        provenance: false  # Avoids metadata issues if GitHub is strict

    - name: Deploy to Docker Swarm via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SWARM_HOST }}
        username: ${{ secrets.SWARM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stack deploy -c /docker/stacks/${{ github.event.repository.name }}/docker-compose.yml ${{ github.event.repository.name }}
